[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "node index.js"

[variables]
NODE_ENV = "production"