[build]
builder = "dockerfile"

[deploy]
startCommand = "node index.js"
healthcheckPath = "/api/bot-status"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
numReplicas = 1

[env]
NODE_ENV = "production"
PORT = "5000"